# Generated by Django 4.2 on 2023-08-30 17:12

import datetime
import decode_blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=decode_blogs.models.uniq_name_upload)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 30, 23, 12, 6, 211372))),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decode_blogs.category')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
