# Generated by Django 3.2.20 on 2023-09-08 14:50

import datetime
import decode_blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blogs', '0006_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=decode_blogs.models.uniq_name_upload)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 8, 20, 50, 24, 726060))),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decode_blogs.category')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
