# Generated by Django 3.2.20 on 2023-10-01 08:18

import datetime
import decode_blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blogs', '0032_auto_20231001_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 14, 18, 27, 989651)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 14, 18, 27, 990653)),
        ),
        migrations.CreateModel(
            name='EditBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=decode_blogs.models.uniq_name_upload)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 1, 14, 18, 27, 990653))),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decode_blogs.category')),
            ],
            options={
                'verbose_name': 'EditBlog',
                'verbose_name_plural': 'BlogsEdit',
            },
        ),
    ]
