# Generated by Django 3.2.20 on 2023-10-01 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blogs', '0033_auto_20231001_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 15, 13, 45, 938688)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 15, 13, 45, 940687)),
        ),
        migrations.AlterField(
            model_name='editblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 15, 13, 45, 939688)),
        ),
    ]
