# Generated by Django 3.2.20 on 2023-10-01 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blogs', '0035_auto_20231001_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 35, 49, 983351)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 35, 49, 985352)),
        ),
        migrations.AlterField(
            model_name='editblogmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 35, 49, 984351)),
        ),
    ]
