# Generated by Django 3.2.20 on 2023-09-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decode_authe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
